# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ev < Formula
  desc "Secure, lightweight CLI for managing environment variables"
  homepage "https://github.com/hugovntr/ev"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugovntr/ev/releases/download/v0.1.0/ev_0.1.0_darwin_amd64.tar.gz"
      sha256 "bfbfd22a8e5b1aec8d5201b6f5c817526b8cb78ed22344afbe1ea22dda8f933a"

      def install
        bin.install "ev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugovntr/ev/releases/download/v0.1.0/ev_0.1.0_darwin_arm64.tar.gz"
      sha256 "420b0d9018357f14ff7a7abaf8a1716639042cbaf53ea6b050edb4f9294782de"

      def install
        bin.install "ev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugovntr/ev/releases/download/v0.1.0/ev_0.1.0_linux_amd64.tar.gz"
      sha256 "eff9edda7b28ad8258f191b6f4ebae2f5f19045fab3294a6709fc3398b788e4d"
      def install
        bin.install "ev"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugovntr/ev/releases/download/v0.1.0/ev_0.1.0_linux_arm64.tar.gz"
      sha256 "eb7b45eff1b26620b49f54071f22f56fac56060172771e4aca05310b7609eca0"
      def install
        bin.install "ev"
      end
    end
  end

  test do
    system "#{bin}/ev --version"
  end
end
